### PR TITLE
Feat/add contains link descriptor

### LINKED ISSUE #1313: Add a new `ContainsLink` descriptor to Evidently
About Hacktoberfest contributions: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest-2024

**Description**:

Add a new `ContainsLink` descriptor that checks if the text contains any valid hyperlinks.  It returns True if at least one valid URL is detected in the text and False if no links are found. 

This can be useful for tasks such as checking that LLM-generated response includes a reference link when it is expected.

### PR DESCRIPTION
**Pull request by Sifr-un**
Implementing "contains link" descriptor.
Resolves #1313

### CODE REVIEW

**Comment by emeli-dral** [comment]
Hi @Rayryu,
Apologies for the delay in reviewing your PR. Thank you for your hard work—the implementation looks great! Could you please add the new descriptor to the list of descriptors under the TextEvals heading on the [documentation page](https://docs.evidentlyai.com/reference/all-metrics#text-evals-1)? Once that’s done, we’ll be ready to proceed with the merge.

Thanks again!

**Comment by Rayryu** [comment]
> Hi @Rayryu, Apologies for the delay in reviewing your PR. Thank you for your hard work—the implementation looks great! Could you please add the new descriptor to the list of descriptors under the TextEvals heading on the [documentation page](https://docs.evidentlyai.com/reference/all-metrics#text-evals-1)? Once that’s done, we’ll be ready to proceed with the merge.
> 
> Thanks again!

No worries @emeli-dral ! I've added the descriptor under the TextEvals 👌

**Comment by emeli-dral** [comment]
Hi @Rayryu,

Apologies for any confusion regarding the documentation. It looks like you've made changes to the ```TextEvals``` preset itself, which is a bit different. If we keep that change, this descriptor will be included in the preset by default, which isn’t quite what we're aiming for.

I was referring to the documentation only! The document is located here: [all-metrics.md#text-evals](https://github.com/evidentlyai/evidently/blob/main/docs/book/reference/all-metrics.md#text-evals).

Could I kindly ask you to revert the changes to the ```TextEvals``` preset itself and just add a line to the documentation?

Feel free to use the other descriptors as a reference! :)

**Comment by Rayryu** [comment]
> Apologies for any confusion regarding the documentation. It looks like you've made changes to the `TextEvals` preset itself, which is a bit different. If we keep that change, this descriptor will be included in the preset by default, which isn’t quite what we're aiming for.
> 
> I was referring to the documentation only! The document is located here: [all-metrics.md#text-evals](https://github.com/evidentlyai/evidently/blob/main/docs/book/reference/all-metrics.md#text-evals).
> 
> Could I kindly ask you to revert the changes to the `TextEvals` preset itself and just add a line to the documentation?
> 
> Feel free to use the other descriptors as a reference! :)

Thanks for the clarification! I see what happened now. I'll revert the changes to the TextEvals preset and update the documentation as you suggested. Appreciate your patience and guidance on this!

**Pull request merged**
