### PR TITLE
added hellinger_distance unittest and updated doc

### PR DESCRIPTION
**Pull request by inderpreetsingh01**
**Issue:**
 #347 (Hellinger distance for drift analysis)

**What does this implement/fix?**
Adds unittests for hellinger_distance drift detection test

@emeli-dral Please let me know if any changes are required. Thanks

### CODE REVIEW

**Comment by inderpreetsingh01** [comment]
@emeli-dral I ran black for test_stattests.py at my end but got no changes.

**Comment by inderpreetsingh01** [comment]
Hi @emeli-dral can you please review this pr, thanks.

**Comment by emeli-dral** [comment]
Hey @inderpreetsingh01 ,
First of all I apologise for the late reply.

I went through the updated test implementation and I have a question to discuss.
I took the following data
```
q = pd.Series([1,1,1,1,1]*10)
```
and tried to call _hellinger_distance function with different feature_type parameter. 
I got a bit surprising results:
```
_hellinger_distance(q, q, feature_type='num', threshold=0.1)
Out: (1.0, True)

_hellinger_distance(q, q, feature_type='cat', threshold=0.1)
Out: (0.0, False)
```

Could you please take a look and double check the implementation for numerical case?

**Comment by inderpreetsingh01** [comment]
@emeli-dral thanks for pointing out the issue, I have made the changes and added this case in test_stattests.py as well, let me know if any further changes are needed.

**Comment by inderpreet-adapdix** [comment]
Hi @emeli-dral are there any changes required in this pr before it can be merged?

**Comment by inderpreetsingh01** [comment]
Hi @emeli-dral are there any changes required in this pr before it can be merged?

**Comment by emeli-dral** [comment]
> Hi @emeli-dral are there any changes required in this pr before it can be merged?

Hi @inderpreetsingh01!
Could you please solve conflicts in your branch?

**Comment by inderpreetsingh01** [comment]
Hi @emeli-dral, I have resolved the merge conflicts.

**Comment by emeli-dral** [comment]
@inderpreetsingh01 thank you for your contribution!

**Comment by dmaliugina** [comment]
Hey @inderpreetsingh01! Thank you for your contribution! My name is Dasha, I'm a community host at Evidently. We've been chatting recently with other contributors to ask what drives them to contribute to open source. Could you please share what drives you as well? 

If you feel like it, please join our Discord community :) There we celebrate our contributors and chat about applied ML https://discord.gg/YQuXNWameG

**Pull request merged**
