### PR TITLE
ExactMatch descriptor

### LINKED ISSUE #1312: Add a new `ExactMatch` descriptor to Evidently
# Add an `ExactMatch()` Descriptor

About Hacktoberfest contributions: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest-2024

**Description:**

The `ExactMatch()` descriptor will compare text between two columns and return `True` if the text in both columns matches exactly, and `False` otherwise.

It should accept `with_column` parameter similar to `SemanticSimilarity` descriptor.

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
Added a ExactMatch descriptor

PR closes #1312

### CODE REVIEW

**Comment by gagan-bhullar-tech** [comment]
Fixed pipeline. Please review.

**Comment by emeli-dral** [comment]
Hi @gagan-bhullar-tech , 
Thank you for your submission! You've done a great job so far.

I’ve tested the implementation, and here’s a sample code to verify if the descriptor works as expected:

```
import pandas as pd

from evidently import ColumnMapping
from evidently.report import Report
from evidently.metric_preset import TextEvals
from evidently.descriptors import ExactMatch

data = {
        "generated": [
            "This is the same",
            'This is not the same',
        ],
        "second_generated": [
            "This is the same",
            'This is the same',
        ],
    }

df = pd.DataFrame(data)

report = Report(metrics=[
    TextEvals(column_name="generated", descriptors=[
        ExactMatch(with_column="second_generated")
            ]
        )
])

report.run(reference_data=None, current_data=df)
report
```
When running this code, an error occurs because a Series object is returned, whereas we expected a DataFrame. The issue originates in the generate_feature function in exact_match_feature.py.

Please take a look at the function signature and the type of the returned object. The issue will be resolved by returning a DataFrame instead of a Series. For instance, you can update the function like this:
```
def generate_feature(self, data: pd.DataFrame, data_definition: DataDefinition) -> pd.DataFrame:
        return pd.DataFrame({self._feature_name(): data[self.columns[0]] == data[self.columns[1]]})
```

I suggest the following next steps:
1/ Fix the ```generate_feature ```Function: Update the function to return a DataFrame and ensure the report is generated correctly.
2/ Please add the new descriptor to the list of descriptors under the ```TextEvals``` heading on the [documentation page](https://docs.evidentlyai.com/reference/all-metrics#text-evals-1).

Once these changes are made, we’ll be ready to merge your PR!

Thanks again for your contribution!🙏

**Comment by gagan-bhullar-tech** [comment]
@emeli-dral updated PR. Please review.

**Comment by emeli-dral** [comment]
@gagan-bhullar-tech almost there! 
Here is a test for ```exact_match feature```, which needs to be fixed. Please, take a look at the output of any failed test.

**Comment by gagan-bhullar-tech** [comment]
@emeli-dral fixed tests

**Comment by emeli-dral** [comment]
Hey @gagan-bhullar-tech,
We recently made a small change related to pip-audit. Could you please rebase your branch to incorporate this update? I believe it should help all the tests pass, and we’ll be able to move forward with the merge.

Thanks!

**Comment by gagan-bhullar-tech** [comment]
@emeli-dral updated PR

**Comment by emeli-dral** [comment]
Hi @gagan-bhullar-tech,
Well done, and thank you so much for your hard work! We’ll go ahead and proceed with the merge🚀

**Pull request merged**
