### PR TITLE
MobAd BigData Beeline Kazakhstan: add lift table and lift curve metrics

### PR DESCRIPTION
**Pull request by IlmuratTokhtakhunov**
These commits allow you to add lift table and lift curve metrics to the Evidently common library, all metrics have inherited behavior and integrations of standard Evidently metrics, these metrics were designed by Tokhtakhunov Ilmurat, BigData Analyst of Mobile Advertising and GEO team in the BigData department at Beeline Kazakhstan, as an Evidently library extension for models performance monitoring.

### CODE REVIEW

**Comment by alimbekovKZ** [comment]
Hi @emeli-dral 

We have added lift table and lift curve metrics to Evidently
There are now problems with CI / linter and we won’t organize something to figure it out =)
We can watch together and do MR

Thank you

**Comment by Liraim** [comment]
There is misleading documentation about black (we will fix it).
You need to execute
```
black -l 120 -t py37 src
black -l 120 -t py37 tests
```

You can add `--check --diff` if you want to see changes only without modifying files by black.

**Comment by IlmuratTokhtakhunov** [comment]
Hello @emeli-dral, @Liraim, @mnrozhkov,

We have just updated the scripts to meet the CI/linter requirements. Therefore, the scripts are now ready for the next CI/linter check

Thank you

**Comment by alimbekovKZ** [comment]
Hello @emeli-dral , @Liraim 
Can you review this MR?

Thank you

**Pull request merged**
