### PR TITLE
added how to use column mapping notebook

### PR DESCRIPTION
**Pull request by AntonisCSt**
Added most of the examples like Elena asked in the **Issue : #552** and the docs mention in: https://docs.evidentlyai.com/user-guide/input-data/column-mapping#prediction-column-s-in-classification

The notebook misses the:
* Text case
* Binary probabilistic classification, option 1
* Binary probabilistic classification, option 2

If you want I can include such examples

Also, I can cut some already existing examples to make the notebook lighter and smaller.

### CODE REVIEW

**Comment by AntonisCSt** [comment]
Hi @emeli-dral thanks so much for the feedback. Already started adding everything you suggested and be happy to include text and embedding examples.

I just have a question:

Shouldn't the example code documentation( [Column Map](https://docs.evidentlyai.com/user-guide/input-data/column-mapping) ) in  **Binary probabilistic classification, option 1** and **Binary probabilistic classification, option 2** be

`column_mapping.pos_label = 'churn'` instead of `pos_label = 'churn'`  ?

**Comment by elenasamuylova** [comment]
Hi @AntonisCSt, thanks for noticing! You are correct; we'll fix it in the docs too.

**Comment by emeli-dral** [comment]
Hey @AntonisCSt ,
While reviewing the example, we found an internal issue with ```target_names```  usage in ```ClassificationConfusionMatrix```.  Here is the [link](https://colab.research.google.com/drive/1sdAz9wAyI7YmY6QTYHVscibaPRVuRxOY?authuser=1#scrollTo=GxFF_eGar-7v) in case you want to see what is broken. 
We need to make a minor fix before merging this PR to ensure the example works. We hope to resolve it in a few days.

**Comment by AntonisCSt** [comment]
I see, thanks for letting me know!

I had the impression that I ran everything successfully before committing.😅

**Pull request merged**
