### PR TITLE
IsValidJSON() descriptor

### LINKED ISSUE #1316: Add a new `IsValidJSON()` descriptor to Evidently
About Hacktoberfest contributions: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest-2024

**Description**

Add the `IsValidJSON()` descriptor that checks whether the text in a specified column is a valid JSON object. It returns True if the text can be parsed as valid JSON and False if it cannot.

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
Added a descriptor for IsValidJSON()

PR closes #1316

### CODE REVIEW

**Comment by emeli-dral** [comment]
Hi @gagan-bhullar-tech ,
thank you for your contribution!
It was pleasure to review it, from the technical point of view everything looks really good 👍  

I only have two requests:
1/ one regarding the naming. Could you please rename the descriptor from ```IsJSONValid()``` to ```IsValidJSON()```. We prefer to maintain consistency across all descriptors by using statement formats rather than questions for the naming convention.

2/ and one more regarding the dosc. Could you please add the descriptor to the list of all descriptors under Text Evals heading on [the documentation page.](https://docs.evidentlyai.com/reference/all-metrics#text-evals-1)

**Comment by gagan-bhullar-tech** [comment]
@emeli-dral updated PR. Please review.

**Comment by emeli-dral** [comment]
@gagan-bhullar-tech 
Thanks for the update! It looks great 👍 
Let's fix tests and we merge it. 
Please take a look at error messages (I believe messages are the same in all tests), it is something minor with class paths registration.

**Comment by gagan-bhullar-tech** [comment]
@emeli-dral updated PR

**Comment by gagan-bhullar-tech** [comment]
@emeli-dral not sure why that single test is failing. This does not look like related to my code.

**Comment by emeli-dral** [comment]
Hi @gagan-bhullar-tech,
All tests have successfully passed, and we’re ready to merge your PR!
Thank you for your hard work!

**Pull request merged**
