### PR TITLE
Fix docs and example on classification column mapping

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
This PR fixes the issue described in #800 
Please review and let me know in case of any feedback.

### CODE REVIEW

**Comment by emeli-dral** [comment]
Hi @ujwalkumar1995 ,
Thank you for helping us out!

I like it a lot, and here is a small comment:
1. I noticed that there  is one more place in the example where pos_label is not set properly:
Screenshot 2023-10-04 at 23 38 37

Could you please update it as well?

2. We also prefer to have ```.ipynb``` examples to be stored in the repo without cell output. Could you please remove he output from all cells before you commit the example to the repo?

**Comment by ujwalkumar1995** [comment]
Hey @emeli-dral 
Thank you for the feedback.
Do we need to remove the output cell from all the ipybb files or are we looking for a particular subset of files?

**Comment by emeli-dral** [comment]
Well, ideally we want to remove the output cell from all the ipynb files. Practically we start from sample_notebooks and how_to_questions :)

**Comment by ujwalkumar1995** [comment]
Hey @emeli-dral 
Have made the suggested changes. Kindly review.

**Comment by emeli-dral** [comment]
@ujwalkumar1995 Thanks a lot!

**Pull request merged**
